import pyautogui
import webbrowser
import time

def adjustscale(coord):
    return (coord[0]/2, coord[1]/2)

webbrowser.open_new('https://www.jetpunk.com/quizzes/how-many-countries-can-you-name')
time.sleep(5)
coord = pyautogui.locateCenterOnScreen('start.png')#Error with mac need to divide by 2
pyautogui.click(adjustscale(coord))
pyautogui.typewrite('AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ArgentinaArmeniaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBhutanBoliviaBosnia BotswanaBrazilBruneiBulgariaBurundiCambodiaCameroonCanadaCape VerdeChadChileChinaColombiaComorosCongoCosta RicaCroatiaCubaCyprusCzech RepublicDenmarkDjiboutiDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFijiFinlandFranceGabonGambiaGeorgiaGermanyGhanaGreeceGrenadaGuatemalaGuineaGuinea-BissauGuyanaHaitiHondurasHungaryIcelandIndiaIndonesiaIranIraqIreland IsraelItalyIvory CoastJamaicaJapanJordanKazakhstanKenyaKiribatiNorth KoreaSouth Korea KosovoKuwaitKyrgyzstanLaosLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacedoniaMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMauritaniaMauritiusMexicoMicronesiaMoldovaMonacoMongoliaMontenegroMoroccoMozambiqueMyanmar NamibiaNauruNepalNetherlandsNew ZealandNicaraguaNigerNigeriaNorwayOmanPakistanPalauPanamaPapua New GuineaParaguayPeruPhilippinesPolandPortugalQatarRomaniaRussia RwandaSt kittsSt LuciaSaint VincentSamoaSan MarinoSao TomeSaudi ArabiaSenegalSerbiaSeychellesSierra LeoneSingaporeSlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth SudanSpainSri LankaSudanSurinameSwazilandSwedenSwitzerlandSyriaTaiwanTajikistanTanzaniaThailandTogoTongaTrinidadTunisiaTurkeyTurkmenistanTuvaluUgandaUnited Arab EmiratesUnited KingdomUnited StatesUruguayUzbekistanVanuatuVatican VenezuelaVietnamYemenZambiaZimbabweBurkina FasoCentral African RepublicUkraine',interval=0.00000000000000000000000000000000000001)
